use crate::action::{Action, EditorAction, FileExplorerAction, Motion, UndoTreeAction};
use crate::key::Key;
use crate::keymap::{KeyContext, KeyMap};

/// Register default keybindings
pub fn register_defaults(keymap: &mut KeyMap) {
    // File Explorer Defaults
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('q'),
        Action::Explorer(FileExplorerAction::Close),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Escape,
        Action::Explorer(FileExplorerAction::Close),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('j'),
        Action::Explorer(FileExplorerAction::Down),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::ArrowDown,
        Action::Explorer(FileExplorerAction::Down),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('k'),
        Action::Explorer(FileExplorerAction::Up),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::ArrowUp,
        Action::Explorer(FileExplorerAction::Up),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Enter,
        Action::Explorer(FileExplorerAction::Select),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Backspace,
        Action::Explorer(FileExplorerAction::Parent),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('-'),
        Action::Explorer(FileExplorerAction::Parent),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char(' '),
        Action::Explorer(FileExplorerAction::ToggleSelection),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('a'),
        Action::Explorer(FileExplorerAction::SelectAll),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('u'),
        Action::Explorer(FileExplorerAction::ClearSelection),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('R'),
        Action::Explorer(FileExplorerAction::Refresh),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('.'),
        Action::Explorer(FileExplorerAction::ToggleHidden),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('l'),
        Action::Explorer(FileExplorerAction::ToggleMetadata),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('n'),
        Action::Explorer(FileExplorerAction::NewFile),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('N'),
        Action::Explorer(FileExplorerAction::NewDir),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('d'),
        Action::Explorer(FileExplorerAction::Delete),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('r'),
        Action::Explorer(FileExplorerAction::Rename),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Char('c'),
        Action::Explorer(FileExplorerAction::Copy),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::Home,
        Action::Explorer(FileExplorerAction::Top),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::End,
        Action::Explorer(FileExplorerAction::Bottom),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::ArrowLeft,
        Action::Explorer(FileExplorerAction::Parent),
    );
    keymap.register(
        KeyContext::FileExplorer,
        Key::ArrowRight,
        Action::Explorer(FileExplorerAction::Select),
    );

    // Undotree Defaults
    keymap.register(
        KeyContext::UndoTree,
        Key::Char('j'),
        Action::UndoTree(UndoTreeAction::Down),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::ArrowDown,
        Action::UndoTree(UndoTreeAction::Down),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::Char('k'),
        Action::UndoTree(UndoTreeAction::Up),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::ArrowUp,
        Action::UndoTree(UndoTreeAction::Up),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::Enter,
        Action::UndoTree(UndoTreeAction::Select),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::Escape,
        Action::UndoTree(UndoTreeAction::Close),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::Char('q'),
        Action::UndoTree(UndoTreeAction::Close),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::Home,
        Action::UndoTree(UndoTreeAction::Top),
    );
    keymap.register(
        KeyContext::UndoTree,
        Key::End,
        Action::UndoTree(UndoTreeAction::Bottom),
    );

    // Normal Mode Defaults
    keymap.register(
        KeyContext::Normal,
        Key::Char('h'),
        Action::Editor(EditorAction::Move(Motion::Left)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('j'),
        Action::Editor(EditorAction::Move(Motion::Down)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('k'),
        Action::Editor(EditorAction::Move(Motion::Up)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('l'),
        Action::Editor(EditorAction::Move(Motion::Right)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('q'),
        Action::Editor(EditorAction::Quit),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('n'),
        Action::Editor(EditorAction::Move(Motion::NextMatch)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('N'),
        Action::Editor(EditorAction::Move(Motion::PreviousMatch)),
    );
    // Word Motion
    keymap.register(
        KeyContext::Normal,
        Key::Char('w'),
        Action::Editor(EditorAction::Move(Motion::NextWord)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('b'),
        Action::Editor(EditorAction::Move(Motion::PreviousWord)),
    );
    // Line Motion
    keymap.register(
        KeyContext::Normal,
        Key::Char('0'),
        Action::Editor(EditorAction::Move(Motion::StartOfLine)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('$'),
        Action::Editor(EditorAction::Move(Motion::EndOfLine)),
    );
    // Paragraph Motion
    keymap.register(
        KeyContext::Normal,
        Key::Char('}'),
        Action::Editor(EditorAction::Move(Motion::NextParagraph)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('{'),
        Action::Editor(EditorAction::Move(Motion::PreviousParagraph)),
    );
    // Sentence Motion
    keymap.register(
        KeyContext::Normal,
        Key::Char(')'),
        Action::Editor(EditorAction::Move(Motion::NextSentence)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('('),
        Action::Editor(EditorAction::Move(Motion::PreviousSentence)),
    );
    // Page Motion
    keymap.register(
        KeyContext::Normal,
        Key::PageUp,
        Action::Editor(EditorAction::Move(Motion::PageUp)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::PageDown,
        Action::Editor(EditorAction::Move(Motion::PageDown)),
    );
    // Undo/Redo
    keymap.register(
        KeyContext::Normal,
        Key::Char('u'),
        Action::Editor(EditorAction::Undo),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Ctrl(b'r'),
        Action::Editor(EditorAction::Redo),
    );
    // Modes
    keymap.register(
        KeyContext::Normal,
        Key::Char('i'),
        Action::Editor(EditorAction::EnterInsertMode),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char(':'),
        Action::Editor(EditorAction::EnterCommandMode),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('/'),
        Action::Editor(EditorAction::EnterSearchMode),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('a'),
        Action::Editor(EditorAction::EnterInsertModeAfter),
    );
    // Normal Mode Arrows/Home/End
    keymap.register(
        KeyContext::Normal,
        Key::ArrowLeft,
        Action::Editor(EditorAction::Move(Motion::Left)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::ArrowRight,
        Action::Editor(EditorAction::Move(Motion::Right)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::ArrowUp,
        Action::Editor(EditorAction::Move(Motion::Up)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::ArrowDown,
        Action::Editor(EditorAction::Move(Motion::Down)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Home,
        Action::Editor(EditorAction::Move(Motion::StartOfLine)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::End,
        Action::Editor(EditorAction::Move(Motion::EndOfLine)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlArrowLeft,
        Action::Editor(EditorAction::Move(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlArrowRight,
        Action::Editor(EditorAction::Move(Motion::NextWord)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlArrowUp,
        Action::Editor(EditorAction::Move(Motion::PreviousParagraph)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlArrowDown,
        Action::Editor(EditorAction::Move(Motion::NextParagraph)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlHome,
        Action::Editor(EditorAction::Move(Motion::StartOfFile)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::CtrlEnd,
        Action::Editor(EditorAction::Move(Motion::EndOfFile)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('x'),
        Action::Editor(EditorAction::Delete(Motion::Right)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('?'),
        Action::Editor(EditorAction::ToggleDebug),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Escape,
        Action::Editor(EditorAction::EnterNormalMode),
    );
    keymap.register(
        KeyContext::Insert,
        Key::ArrowLeft,
        Action::Editor(EditorAction::Move(Motion::Left)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::ArrowRight,
        Action::Editor(EditorAction::Move(Motion::Right)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::ArrowUp,
        Action::Editor(EditorAction::Move(Motion::Up)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::ArrowDown,
        Action::Editor(EditorAction::Move(Motion::Down)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Home,
        Action::Editor(EditorAction::Move(Motion::StartOfLine)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::End,
        Action::Editor(EditorAction::Move(Motion::EndOfLine)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Backspace,
        Action::Editor(EditorAction::Delete(Motion::Left)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Delete,
        Action::Editor(EditorAction::Delete(Motion::Right)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Enter,
        Action::Editor(EditorAction::InsertChar('\n')),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Tab,
        Action::Editor(EditorAction::InsertChar('\t')),
    );
    keymap.register(
        KeyContext::Insert,
        Key::PageUp,
        Action::Editor(EditorAction::Move(Motion::PageUp)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::PageDown,
        Action::Editor(EditorAction::Move(Motion::PageDown)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::CtrlArrowLeft,
        Action::Editor(EditorAction::Move(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::CtrlArrowRight,
        Action::Editor(EditorAction::Move(Motion::NextWord)),
    );
    keymap.register(
        KeyContext::Insert,
        Key::Ctrl(b'w'),
        Action::Editor(EditorAction::Delete(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Command,
        Key::Escape,
        Action::Editor(EditorAction::EnterNormalMode),
    );
    keymap.register(
        KeyContext::Search,
        Key::Escape,
        Action::Editor(EditorAction::EnterNormalMode),
    );
    // Submit
    keymap.register(
        KeyContext::Command,
        Key::Enter,
        Action::Editor(EditorAction::Submit),
    );
    keymap.register(
        KeyContext::Search,
        Key::Enter,
        Action::Editor(EditorAction::Submit),
    );
    // Backspace
    keymap.register(
        KeyContext::Command,
        Key::Backspace,
        Action::Editor(EditorAction::Delete(Motion::Left)),
    );
    keymap.register(
        KeyContext::Search,
        Key::Backspace,
        Action::Editor(EditorAction::Delete(Motion::Left)),
    );
    keymap.register(
        KeyContext::Command,
        Key::Delete,
        Action::Editor(EditorAction::Delete(Motion::Right)),
    );
    keymap.register(
        KeyContext::Search,
        Key::Delete,
        Action::Editor(EditorAction::Delete(Motion::Right)),
    );
    keymap.register(
        KeyContext::Command,
        Key::ArrowLeft,
        Action::Editor(EditorAction::Move(Motion::Left)),
    );
    keymap.register(
        KeyContext::Search,
        Key::ArrowLeft,
        Action::Editor(EditorAction::Move(Motion::Left)),
    );
    keymap.register(
        KeyContext::Command,
        Key::ArrowRight,
        Action::Editor(EditorAction::Move(Motion::Right)),
    );
    keymap.register(
        KeyContext::Search,
        Key::ArrowRight,
        Action::Editor(EditorAction::Move(Motion::Right)),
    );
    keymap.register(
        KeyContext::Command,
        Key::Home,
        Action::Editor(EditorAction::Move(Motion::StartOfLine)),
    );
    keymap.register(
        KeyContext::Search,
        Key::Home,
        Action::Editor(EditorAction::Move(Motion::StartOfLine)),
    );
    keymap.register(
        KeyContext::Command,
        Key::End,
        Action::Editor(EditorAction::Move(Motion::EndOfLine)),
    );
    keymap.register(
        KeyContext::Search,
        Key::End,
        Action::Editor(EditorAction::Move(Motion::EndOfLine)),
    );
    keymap.register(
        KeyContext::Command,
        Key::CtrlArrowLeft,
        Action::Editor(EditorAction::Move(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Search,
        Key::CtrlArrowLeft,
        Action::Editor(EditorAction::Move(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Command,
        Key::CtrlArrowRight,
        Action::Editor(EditorAction::Move(Motion::NextWord)),
    );
    keymap.register(
        KeyContext::Search,
        Key::CtrlArrowRight,
        Action::Editor(EditorAction::Move(Motion::NextWord)),
    );
    keymap.register(
        KeyContext::Command,
        Key::Ctrl(b'w'),
        Action::Editor(EditorAction::Delete(Motion::PreviousWord)),
    );
    keymap.register(
        KeyContext::Search,
        Key::Ctrl(b'w'),
        Action::Editor(EditorAction::Delete(Motion::PreviousWord)),
    );
    // History navigation
    keymap.register(
        KeyContext::Command,
        Key::ArrowUp,
        Action::Editor(EditorAction::HistoryUp),
    );
    keymap.register(
        KeyContext::Search,
        Key::ArrowUp,
        Action::Editor(EditorAction::HistoryUp),
    );
    keymap.register(
        KeyContext::Command,
        Key::ArrowDown,
        Action::Editor(EditorAction::HistoryDown),
    );
    keymap.register(
        KeyContext::Search,
        Key::ArrowDown,
        Action::Editor(EditorAction::HistoryDown),
    );
    keymap.register(
        KeyContext::Command,
        Key::Ctrl(b'p'),
        Action::Editor(EditorAction::HistoryUp),
    );
    keymap.register(
        KeyContext::Search,
        Key::Ctrl(b'p'),
        Action::Editor(EditorAction::HistoryUp),
    );
    keymap.register(
        KeyContext::Command,
        Key::Ctrl(b'n'),
        Action::Editor(EditorAction::HistoryDown),
    );
    keymap.register(
        KeyContext::Search,
        Key::Ctrl(b'n'),
        Action::Editor(EditorAction::HistoryDown),
    );

    // Operators
    keymap.register(
        KeyContext::Normal,
        Key::Char('d'),
        Action::Editor(EditorAction::Operator(crate::action::OperatorType::Delete)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('c'),
        Action::Editor(EditorAction::Operator(crate::action::OperatorType::Change)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('y'),
        Action::Editor(EditorAction::Operator(crate::action::OperatorType::Yank)),
    );

    // Sequences
    keymap.register_sequence(
        KeyContext::Normal,
        vec![Key::Char('d'), Key::Char('d')],
        Action::Editor(EditorAction::DeleteLine),
    );
    keymap.register_sequence(
        KeyContext::Normal,
        vec![Key::Char('g'), Key::Char('g')],
        Action::Editor(EditorAction::Move(Motion::StartOfFile)),
    );
    keymap.register(
        KeyContext::Normal,
        Key::Char('G'),
        Action::Editor(EditorAction::Move(Motion::EndOfFile)),
    );
}
